version: '3.9'


networks:
  demo:
    driver: bridge

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local


services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - demo

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - demo

  webapi:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        versao: 1
    image: technobre/demo-api-metrics:latest
    ports:
      - "8080:80"
    networks:
      - demo
